---
title: "Navin Lab - CNA dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: flatly
    logo: navin_lab_logo.png
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(here)
library(fs)
library(cowplot)
library(shiny)
library(janitor)
library(ape)
library(ggtree)
library(ggsci)
library(plotly)
library(amap)
library(paletteer)
library(scales)
library(umap)
library(dbscan)
library(ComplexHeatmap)
library(flsa)
```

```{r, include=FALSE}
# reading data
dat_seg <- readr::read_tsv(fs::dir_ls(path = here(), recursive = T, glob= "*uber*seg.txt"))
dat_bin <- readr::read_tsv(fs::dir_ls(path = here(), recursive = T, glob= "*uber*bin.txt"))
dat_stats <- readr::read_tsv(fs::dir_ls(path = here(), recursive = T, regex= "all_stat_metrics.txt")) %>% 
  janitor::clean_names() %>% 
  mutate(duplicates = dups_removed/total_reads)

# reading ratio
dat_rat <- readr::read_tsv(fs::dir_ls(path = here(), recursive = T, glob= "*uber*ratio.txt"))
dat_rat_cp <- dat_rat %>% dplyr::select(-chrom, -chrompos, -abspos)

# dat_seg setup
dat_seg_s <- dat_seg %>% 
  dplyr::select(-chrom, -chrompos, - abspos)

dat_seg_t <- as.data.frame(t(dat_seg_s))

# sourcing integer inference
source(here::here("bin", "integer_cn.R"))
```
```{r umap_snn, include = FALSE}
dat_umap <- umap::umap(dat_seg_t, random_state= 42, metric = "euclidean")
  
umap_df <- data.frame(umap1 = dat_umap$layout[,1],
                        umap2 = dat_umap$layout[,2])
  
cl <- dbscan::sNNclust(umap_df, k = 20, eps = 2, minPts = 5)

# ordering cells
dat_seg_order <- dat_seg_t[order(cl$cluster),]

# setting colors
row_col <- setNames(paletteer_d(ggsci, 
                                nrc_npg, 
                                length(levels(as.factor(cl$cluster)))),
                    levels(as.factor(cl$cluster)))
```

Summary
=======================================================================

Row
-----------------------------------------------------------------------

### Cells

```{r}
dat_seg %>% 
  dplyr::select(-chrom, -chrompos, -abspos) %>% 
  ncol() %>% 
  valueBox(icon = "circle")
```

### Median PCR Duplicates

```{r}
median(dat_stats$duplicates) %>% 
  scales::percent() %>% 
  valueBox(icon = "percentage")
```


### UMAP

```{r}
p_umap <- umap_df %>% 
  rownames_to_column(var = "Cell") %>%
  dplyr::mutate(cluster = cl$cluster) %>% 
  dplyr::mutate(Cell = str_extract(Cell, "^[^_]*")) %>% 
  ggplot() +
  geom_point(aes(x = umap1, 
                 y = umap2, 
                 color = as.factor(cluster),
                 label = Cell),
             show.legend = FALSE) +
  scale_color_npg() +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        axis.line = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank()) 

ggplotly(p_umap, tooltip = "Cell")
```

Row
-----------------------------------------------------------------------

### Heatmap {data-height=650}

```{r}
heat_row_col <- rowAnnotation(
  data.frame(clusters = sort(cl$cluster)),
             col = list(clusters = row_col))

ht <- Heatmap(log2(dat_seg_order+1e-3),
              cluster_columns = FALSE,
              cluster_rows = FALSE,
              show_row_names = FALSE,
              show_column_names = FALSE,
              use_raster = TRUE,
              heatmap_legend_param = list(title = "Log2 (Ratio)"))

draw(heat_row_col + ht)
```

### Ploidy Inference {data-height=350}

```{r}
dat_ploidy <- Reduce(rbind, 
                     parallel::mcmapply(function(prof, name) c(name, ploidy.and.peakheight(prof)),
                                        dat_rat_cp, names(dat_rat_cp),
                                        mc.cores= 40, SIMPLIFY=FALSE)) %>% 
  as_tibble() %>% 
  readr::type_convert() %>% 
  dplyr::rename(sample_name = V1) %>% 
  dplyr::mutate(sample_name = str_extract(sample_name, "^[^_]*")) %>% 
  dplyr::mutate(Cell = paste(sample_name, 
                              ": ", 
                              ploidy,
                              sep = ""))

p_ploidy <- ggplot(dat_ploidy) + 
  geom_point(aes(x = ploidy, 
                 y = peak_height, 
                 color = peak_height,
                 label = Cell)) +
  scale_color_paletteer_c(scico, berlin) + 
  scale_x_continuous(breaks = scales::pretty_breaks()) +
  scale_y_continuous(breaks = scales::pretty_breaks()) +
  xlab("Inferred ploidy") +
  ylab("Peak Height (Confidence)")

ggplotly(p_ploidy, tooltip = "Cell")
```

QC
=======================================================================

Row
-----------------------------------------------------------------------

### Reads Kept: Hover mouse over cell for info

```{r}
# creates a index for x and y so I have a square matrix, also creates a lable for plotly
p <- dat_stats %>% 
  mutate(idx_x = rep(1:sqrt(nrow(dat_stats)), length.out = nrow(dat_stats), each = sqrt(nrow(dat_stats)))) %>%
  mutate(idx_y = rep(paste(1:sqrt(nrow(dat_stats)),"a", sep = ""), length.out = nrow(dat_stats)))  %>% 
  dplyr::mutate(sample_name = str_extract(sample_name, "^[^_]*")) %>% 
  dplyr::mutate(Cell = paste(sample_name,
                              "- Reads Kept: ",
                             reads_kept,
                             sep = "")) %>% 
  ggplot() + 
  geom_tile(aes(x = idx_x, 
                y = idx_y, 
                fill = reads_kept,
                label = Cell)) +
  coord_equal() + 
  scale_fill_viridis_c(option = "magma",
                       labels = scales::comma) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_blank()) +
  ylab("") +
  xlab("") 


# ggplotly
ggplotly(p, tooltip = c("Cell")) 
```

### Duplicates percentage: Hover mouse over cell for info

```{r}
# creates a index for x and y so I have a square matrix, also creates a lable for plotly
p_dups <- dat_stats %>% 
  mutate(idx_x = rep(1:sqrt(nrow(dat_stats)), 
                     length.out = nrow(dat_stats), 
                     each = sqrt(nrow(dat_stats)))) %>%
  mutate(idx_y = rep(paste(1:sqrt(nrow(dat_stats)),"a", sep = ""),
                     length.out = nrow(dat_stats)))  %>% 
  dplyr::mutate(sample_name = str_extract(sample_name, "^[^_]*")) %>% 
  dplyr::mutate(Cell = paste(sample_name,
                              "- Duplicates: ",
                             scales::percent(duplicates),
                             sep = "")) %>% 
  ggplot() + 
  geom_tile(aes(x = idx_x, 
                y = idx_y, 
                fill = duplicates,
                label = Cell)) +
  coord_equal() + 
  scale_fill_viridis_c(option = "viridis",
                       labels = scales::percent) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_blank()) +
  ylab("") +
  xlab("") 


# ggplotly
ggplotly(p_dups, tooltip = "Cell") 
```

Row
-----------------------------------------------------------------------

### GC normalized bin read count distribution

```{r}
dat_bin %>% 
  dplyr::select(-chrom, -chrompos, -abspos) %>% 
  purrr::map_dfr(median) %>% 
  gather(key = "cell",
         value = "bin_median") %>% 
  ggplot() +
  geom_histogram(aes(x = bin_median, 
                     y= ..count../sum(..count..)),
                 fill = "white",
                 color = "black") +
  xlab("GC normalized median bin count") +
  ylab("Frequency")
```

Phylogenetics
=======================================================================

Row
-----------------------------------------------------------------------

### Neighbor-Joining tree

```{r}
tree <- ape::nj(
  amap::Dist(dat_seg_order, nbproc = 40)
)

# obtaining colors
list_samples <- split(rownames(dat_seg_order),
                      sort(cl$cluster))
tree <- ggtree::groupOTU(tree, list_samples) 

ggtree(ladderize(tree),
  ladderize = FALSE,
  size = .1) +
  geom_tippoint(aes(color = group), size = .7) +
  scale_colour_manual(values = c("black", row_col)) +
  theme(legend.position = "right")
```

